name: Tag pushed (test)
on:
  push:
    tags:
      - '**'

jobs:
  tag:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hollanddd'

      - name: Setup git
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "<>"

      - name: Extract tag from ref
        id: ref_version
        run: echo "::set-output name=VALUE::${GITHUB_REF:18}"

      - name: Extract package version
        id: pkg_version
        run: |
          echo 'pkg_version<<EOF' >> $GITHUB_ENV
          node -pe "require('./package.json').version" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build changelog
        id: build_changelog
        run: |
          echo 'pkg_changelog<<EOF' >> $GITHUB_ENV
          git log HEAD ^${{ env.pkg_version }} --pretty=%s >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo $pkg_changelog
